---
title: "ICDSS"
author: "Wei Quan"
date: "11/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
knitr::opts_knit$set(root.dir = getwd())
library(tidyverse)
data <- read.csv('data.csv')
```

##Data processing
```{r}
head(data)
prop.table(table(data$IE))
hist(data$IE)
hist(data$testelapse,breaks=100)
summary(data$testelapse)/60

# filter with testlapse in 1% and 99% quantile
data_filter <- data %>%
  filter(IE!=0 & testelapse>= quantile(testelapse,0.01) & testelapse <= quantile(testelapse,0.99) )

data_final <- data_filter %>%
  select(ends_with("A"),IE,age,gender)

# decide dependent value
data_final <- data_final%>%
  mutate(IE_extrovert=ifelse(IE==2,1,0),
         IE_introvert=ifelse(IE==1,1,0))

head(data_final[,1:90])

```

## extrovet analysis
```{r}
# logistic regression
logistic_ex_reg <- function(x){
  summary(glm(data=data_final,IE_extrovert~x,family='binomial'))$coefficient[2,]
}

coef <- apply(data_final[,1:91],2,logistic_ex_reg)[1,]
se <- apply(data_final[,1:91],2,logistic_ex_reg)[2,]
pval <- apply(data_final[,1:91],2,logistic_ex_reg)[4,]
results <- data.frame(cbind(coef,se,pval))
results$Q <- 1:91

p_threshold <- 0.05/91

# Volcano plot ------------------------------------------------
#x:log(coef)
#y:-log(SE)

pval_bonf = 0.05/nrow(results)

library(ggthemes)
library(plotly)

p <- results %>%
  ggplot(aes(x = coef,y = -log10(pval),col=Q,label=rownames(results))) +
  geom_point(size=1.5) +
  geom_hline(yintercept = -log10(pval_bonf),
             col = 'grey40',
             linetype = 'dotted') + 
  annotate('text',x=-1.0, y= -log10(pval_bonf + 0.000001),
             label=paste('p=' ,pval_bonf),
             size=2,col='grey30') +
  theme_few()
  #scale_colour_mannual(name='',
  #                     values=c('grey60','darkorange1','firebrick2'),
  #                     labels=levels(results$significance),
  #                     drop=FALSE) +
p + geom_text(check_overlap = TRUE,aes(size= 1/se^2))
ggplotly(p)

# -log(p) plot ------------------------------------------------

results %>%
ggplot(aes(x=Q,y=-log10(pval),col=Q))+
  geom_point(alpha=0.8,size=1.3)+
  scale_x_continuous() +
  scale_y_continuous(expand = c(0, 0) ) +
  theme_bw() +
  theme( 
    legend.position="none",
    panel.border = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
    )+
  labs(title='-logpval with Extrovert and Questions',
       x='questions',
       y='-logpval')+
  geom_hline(yintercept=p_threshold,color='royalblue')

# logistic regression for predicting
predict_ex <- glm(data=data_final, IE_extrovert ~ Q80A+Q81A+Q84A+Q91A,family='binomial')
summary(predict_ex)
```

## introvert analysis
```{r}
# logistic regression
logistic_in_reg <- function(x){
  summary(glm(data=data_final,IE_introvert~x,family='binomial'))$coefficient[2,]
}

coef_in <- apply(data_final[,1:91],2,logistic_in_reg)[1,]
se_in <- apply(data_final[,1:91],2,logistic_in_reg)[2,]
pval_in <- apply(data_final[,1:91],2,logistic_in_reg)[4,]
results_in <- data.frame(cbind(coef_in,se_in,pval_in))
results_in$Q <- 1:91

p_threshold <- 0.05/91

# Volcano plot ------------------------------------------------
#x:log(coef)
#y:-log(SE)

pval_bonf = 0.05/nrow(results_in)

library(ggthemes)
p_in <- results_in %>%
  ggplot(aes(x = coef_in,y = -log10(pval_in),col=Q,label=rownames(results_in))) +
  geom_point(size=1.5) +
  geom_hline(yintercept = -log10(pval_bonf),
             col = 'grey40',
             linetype = 'dotted') + 
  annotate('text',x=-1.0, y= -log10(pval_bonf + 0.000001),
             label=paste('p=' ,pval_bonf),
             size=2,col='grey30') +
  theme_few()
  #scale_colour_mannual(name='',
  #                     values=c('grey60','darkorange1','firebrick2'),
  #                     labels=levels(results$significance),
  #                     drop=FALSE) +
p_in + geom_text(check_overlap = TRUE,aes(size= 1/se^2))

ggplotly(p_in)

# logistic regression for predicting
predict_in <- glm(data=data_final, IE_introvert ~ Q82A+Q83A+Q91A,family='binomial')
summary(predict_in)
```